export const randomNames = [
  '情歌王子',
  '麦霸本麦',
  '灵魂歌手',
  '寂寞的麦霸',
  '浴室歌神',
  '深情歌者',
  '高音之王',
  '走音大师',
  '假音大师',
  '摇滚狂人',
  'KTV小王子',
  '麦克风终结者',
  '电音之王',
  '情歌王',
  '说唱新星',
  '民谣诗人',
  '甜歌皇后',
  '摇滚大姐大',
  '金曲制造机',
  '原唱杀手'
];

const englishRandomNames = [
  'Ballad Star',
  'Mic Master',
  'Soul Singer',
  'Lonely Crooner',
  'Shower Idol',
  'Velvet Voice',
  'High Note Hero',
  'Pitch Rebel',
  'Falsetto Pro',
  'Rock Legend',
  'KTV Prince',
  'Mic Dropper',
  'Electro King',
  'Love Song Ace',
  'Rap Rookie',
  'Folk Poet',
  'Sweet Song Diva',
  'Rock Queen',
  'Hit Maker',
  'Cover Slayer'
];

export function getRandomNames(language) {
  return language === 'en' ? englishRandomNames : randomNames;
}

export const emojis = [
  '🎤',
  '🎵',
  '🎶',
  '🎧',
  '🎸',
  '🎹',
  '🕺',
  '💃',
  '👑',
  '🌟',
  '🍻',
  '🍿',
  '🔥',
  '✨',
  '👾',
  '🌈',
  '🐱',
  '🦊',
  '🐼',
  '🐨',
  '🐯',
  '🐰',
  '🦁',
  '🦄',
  '🐶',
  '🐸',
  '🐵',
  '🐣',
  '🦖',
  '🐉',
  '🍀',
  '🌸',
  '🍕',
  '🍟',
  '🍦',
  '🍩',
  '🥑',
  '🍔',
  '🍺',
  '🍷',
  '🥂',
  '🍹',
  '🎈',
  '🎉',
  '🎁',
  '🎭',
  '🎪',
  '🎷',
  '🎺',
  '🎻',
  '🥁',
  '📻',
  '📺',
  '📱',
  '🕶️',
  '💅',
  '💄',
  '💍',
  '💎',
  '❤️',
  '💖',
  '💥',
  '🚀',
  '🛸',
  '⭐',
  '🌊',
  '⚡',
  '👻',
  '👽',
  '🤖'
];

export const hotSongs = [
  { title: '七里香', singer: '周杰伦' },
  { title: '晴天', singer: '周杰伦' },
  { title: '后来', singer: '刘若英' },
  { title: '十年', singer: '陈奕迅' },
  { title: '江南', singer: '林俊杰' },
  { title: '倒带', singer: '蔡依林' },
  { title: '泡沫', singer: '邓紫棋' },
  { title: '吻别', singer: '张学友' },
  { title: '消愁', singer: '毛不易' },
  { title: '小情歌', singer: '苏打绿' }
];

const englishHotSongs = [
  { title: 'Yesterday Once More', singer: 'The Carpenters' },
  { title: 'My Heart Will Go On', singer: 'Celine Dion' },
  { title: 'I Want It That Way', singer: 'Backstreet Boys' },
  { title: 'Someone Like You', singer: 'Adele' },
  { title: 'Perfect', singer: 'Ed Sheeran' },
  { title: 'Rolling in the Deep', singer: 'Adele' },
  { title: 'Bohemian Rhapsody', singer: 'Queen' },
  { title: 'Hotel California', singer: 'Eagles' },
  { title: 'Let It Be', singer: 'The Beatles' },
  { title: 'Take Me Home, Country Roads', singer: 'John Denver' }
];

export function getHotSongs(language) {
  return language === 'en' ? englishHotSongs : hotSongs;
}
